### ISSUE TITLE
Add build for ixp4xx architecture

### ISSUE THREAD

**Issue by ttosch** [probonopd/vcontrold-for-openwrt#4]
Hi, would it be possible to add a build for ixp4xx? I am running an NSLU2 with OpenWrt Barrier Breaker 14.07. Thanks very much! --Thomas

**Comment by probonopd** [comment]
Added, see https://github.com/probonopd/vcontrold-for-openwrt/releases

**Comment by ttosch** [comment]
Awesome, thanks!!
