### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Extrabannies** [probonopd/vcontrold-for-openwrt#5]
Hi,

I have now managed to install you ipk on my D-Link DIR-505.

As I have purchased an original OptoLink Adapter from Viessmann with USB connection, pls advise how 
I must change the configuration in the vcontrold.xml file, most of all the port.
Do I need to install any additional Kernel supports?

Any help would be highly appreciated!!
Thank you!

Cheers
Björn

**Comment by probonopd** [comment]
Hello Björn, unfortunately I have never seen an original OptoLink Adapter from Viessmann and thus don't know how to connect it to a D-Link DIR-505. I used some parts (less than 10 EUR cost) to build an infrared sender/receiver unit myself. It is working well for me.

**Comment by Extrabannies** [comment]
Hi,
Danke für die Antwort. Kannst du mir evtl. helfen bei folgendem Problem:
Nach der Installation von openwrt etc. sehe ich kein usb0 oder usb 1 in /dev.
Alle Versuche alles neu zu installieren (alles gemäß openwrt Anleitung) haben nichts gebracht.
Bin irgendwie mit meinem Latein am Ende.
Wäre klasse.
Herzliche Grüße
Björn

**Comment by probonopd** [comment]
The device node /dev/... gets created only if a kernel module matching to the hardware USB-to-serial adapter is installed. Which kernel module(s) did you install?

**Comment by Extrabannies** [comment]
I installed, according http://wiki.openwrt.org/doc/howto/usb.essentials, the following modules:

kmod-usb-core -> no errors

kmod-usb-ohci -> after insmod usb-ohci I get resposne: "Failed to fond usb-ohci. Maybe itis a built in module?"

kmod-usb2 -> no errors

usbutils -> no errors

if a go to /dev I do not see any usb.

an lsusb shows: 
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 002: ID 0403:6001 Future Technology Devices International, Ltd FT232 USB-Serial (UART) IC
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

I am lost. Unfortunately.

**Comment by Extrabannies** [comment]
Hi,
I have found that I have to install a virtuel drive:
kmod-usb-serial-ftdi
Now I see the USB0.
I have now further followed your instructions.
However, if I try to start vcontrold by "./vcontrold start" I get a 
"start-stop deamon: can't execute ... no such file or Directory" although
in /usr/sbin there is a vcontrold.
Do you have any ideas?
Does it have anything to do with the fact, that I changed the device from 2098 to 20B4, as /etc/vcontrold does contain two additional files -> sim-2098.ini and vcontrold_dev-id-2098.xlm?
Cheers
Björn

**Comment by probonopd** [comment]
Sorry, I don't know that. I only compiled vcontrold, and it was working for me. Probably it is best to ask the vcontrold authors at http://sourceforge.net/p/vcontrold/wiki/Home/

**Comment by Extrabannies** [comment]
Thanks for your reply.
Can I ask the question, how you have compiled it?
Could you - am I a newby to everything and Google my only help - provide a version compiled with uClibc?
According to the forums that is the problem.

If I may, certain other questistions:
- Have you sysupgraded your DLINK?
- Have you installed LUCI on your DLINK?

I would be very grateful for your support.
http://unix.stackexchange.com/questions/18061/why-does-sh-say-not-found-when-its-definitely-there
http://stackoverflow.com/questions/31385121/elf-file-exists-in-usr-bin-but-turns-out-ash-file-not-found

**Comment by probonopd** [comment]
Hi, I installed OpenWrt on my DLink (could also have used another router that has USB and is supported by OpenWrt). And I am using a self-built inexpensive IR sender/receiver with a serial-to-USB adapter that is supported by a kernel driver from the OpenWrt repository.

Are you not running OpenWrt? Then this project is not for you.

**Comment by Extrabannies** [comment]
Yes, I installed OpenWRT on my DLink DIR-505.
It is running well.
Via usbip I can even "see" the Optolink Adapter.
However, I like your clean approach.
Thus I would like to access and run the Optolink from the DLink.
Maybee I have installed the .ipk file wrong.
I used "opkg install https://github.com/probonopd/vcontrold-for-openwrt/releases/download/3/vcontrold_106-1_ar71xx.ipk".
Is this correct, or did I miss anything?
Cheers
Björn
PS: Thanks for your Patience.

**Comment by probonopd** [comment]
That does not work because the package manager in OpenWrt cannot download from https but only from http. Copy the ipk to the device using some other way and try installing that.

Which kernel module does the Optolink adapter load?

**Comment by Extrabannies** [comment]
That is what I have actually done. No errors during installation. I have installed an ftdi driver: kmod-usb-serial-ftdi.
No errors encountered.
As said before, when I try to start vcontrold, does not matter whether over the init.d script or directly in usr/sbin I get an "file not found" although I see the file vcontrold and have given read and write permits. I am grateful for any ideas or help.

**Comment by probonopd** [comment]
Very strange. Are you sure you used the ipk for the correct architecture, ar71xx?
Which version of OpenWrt do you have installed?

**Comment by Extrabannies** [comment]
I think so as well. More so as I see that vcontrold is there. I used a version dated 29 September now, as I reinstalled openwrt a couple of times (thougt there was an issue). One time I had a severe error, as the sysupdate I used was newer (higher version over night) than the factory.bin.

**Comment by Extrabannies** [comment]
Hi. I solved the problem by installing vcontrold on my primary server and connecting to the OptoLink via DLINK DIR-505 and ser2net (opkg install ser2net). Thanks for your help and the good idea with the DLINK. A very promising solution and cheap goody to also connect other USB devices with OpenHab.
