### ISSUE TITLE
new architecture

### ISSUE THREAD

**Issue by openvhub** [probonopd/vcontrold-for-openwrt#6]
Hi, would it be possible to add a build for atheros? I am running an fonera 2100 with OpenWrt backfire 10.03.01. Thanks very much! --Tim

**Comment by probonopd** [comment]
Which architecture is this?

**Comment by openvhub** [comment]
Hi,

sorry, I used the wrong wording. I meant new chipset. I would like to use vcontrol on my fonera-2100 (atheros) running openwrt 10.03.1.

Thanks
Tim

Am 15. April 2016 19:04:29 MESZ, schrieb probonopd notifications@github.com:

**Comment by probonopd** [comment]
Yes, which "Atheros chipset"? Each chipset has a name in OpenWrt, such as `ar71xx`.

**Comment by openvhub** [comment]
Hi,

the fonera 2100 uses a MIPS 4KEc CPU.
If looked into the config file for 10.03.1 and found the option Atheros as a chipset to compile for. I thought this would be the right Option to compile for.

Am 18. April 2016 09:08:14 MESZ, schrieb probonopd notifications@github.com:

**Comment by probonopd** [comment]
I see, `atheros`. I have added it to the build job.

**Comment by openvhub** [comment]
Thanks.

Am 19.04.16 um 19:14 schrieb probonopd:

**Comment by probonopd** [comment]
Can now be downloaded from
https://github.com/probonopd/vcontrold-for-openwrt/releases/download/4/vcontrold_106-1_atheros.ipk

**Comment by openvhub** [comment]
Thanks.

Am 19. April 2016 22:54:49 MESZ, schrieb probonopd notifications@github.com:
