### ISSUE TITLE
OpenWrt 18.0.6 and mipsel_24kc

### ISSUE THREAD

**Issue by joker2312** [probonopd/vcontrold-for-openwrt#8]
Hi,
thanks a lot for this wonderful package. I have a TL-WR902AC v3 (target mt76x8), which is only supported since OpenWrt 18.0.0 and does not work with the exitsting vcontrold_106-1_ramips_24kec.ipk binary. Would it be possible to compile a binary for OpenWrt 18.0.6 and a mipsel_24kc architecture?
Many thanks,
--Joern

PS: this should be the link to the sdk.
SDK_URL=https://downloads.openwrt.org/releases/18.06.1/targets/ramips/mt76x8/openwrt-sdk-18.06.1-ramips-mt76x8_gcc-7.3.0_musl.Linux-x86_64.tar.xz

**Comment by probonopd** [comment]
Hi, unfortunately I don't have the time to do this at this time, bu t `.travis.yml` has all the step-by-step information on how to build it, so it should be easy for you to compile it.
